[metadata]
creation_date = "2025/03/16"
maturity = "development"
updated_date = "2025/03/16"

[rule]
author = ["James Spiteri"]
description = "This is a test rule for DAC"
language = "kuery"
name = "This is a test rule for DAC"
risk_score = 50
rule_id = "1718c125-f9eb-4379-8edc-0ffaf62ce6d5"
severity = "high"
type = "query"

query = '''
host.name:*
'''

