[metadata]
creation_date = "2025/03/16"
maturity = "development"
updated_date = "2025/03/16"

[rule]
author = ["James Spiteri"]
description = "This is a 2nd DAC rule"
language = "kuery"
name = "2nd DAC"
risk_score = 50
rule_id = "aa348cb4-43a7-47b7-9b22-6bfa045dbaaa"
severity = "high"
type = "query"

query = '''
host.name:*
'''

