[metadata]
creation_date = "2025/03/17"
maturity = "development"
updated_date = "2025/03/17"

[rule]
author = ["James"]
description = "Newer Rule"
language = "kuery"
name = "New Rule"
risk_score = 50
rule_id = "f797ea0c-b929-442c-80ee-c17e04a9df30"
severity = "high"
type = "query"

query = '''
host.name:*
'''

